version: "3.5"

services:
  gateway:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: hyperdrive_gateway:development
    container_name: hyperdrive_gateway_development
    networks:
      - hyperspace_gateway
    ports:
      - "8080:443" # http/2 server
    volumes:
      - /app/node_modules
      - .:/app
      - hyperspace_storage:/hyperspace_storage
    environment:
      APP_NAME: 'Hyperdrive Gateway'
      HYPERSPACE_STORAGE: /hyperspace_storage
      NODE_ENV: development
      PORT: '443'      
      SSL_KEY: /app/dev-certs/local-computer.key
      SSL_CERT: /app/dev-certs/local-computer.crt
      
networks:
  hyperspace_gateway:
    name: hyperspace_gateway_net

volumes:
  hyperspace_storage: